swagger: "2.0"
info:
  title: Dukedoms of Daleria Game Service API
  version: 0.1.0

paths:
  /newGame:
    post:
      summary: create new Game
      x-swagger-router-controller: controllers.game_endpoints
      operationId: create_new_game
      tags:
        - newGame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: newGameRequest
          description: request to start process of making new game
          schema:
            $ref: '#/definitions/NewGameRequest'
      responses:
        200:
          description: game successfully created
          schema:
            $ref: '#/definitions/NewGameSuccessResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/NewGameFailedResponse'

  /getGame/{gameId}:
    get:
      x-swagger-router-controller: controllers.game_endpoints
      operationId: get_game_info
      tags:
        - getGame
      summary: gets game data by its gameId
      parameters:
        - in: path
          name: gameId
          type: integer
          required: true
          description: integer id of a dukedoms game
      produces:
        - application/json
      responses:
        200:
          description: game successfully retrieved
          schema:
            $ref: '#/definitions/GameInfo'

definitions:
  NewGameRequest:
    type: object
    required:
      - hostPlayer
      - invitedPlayers
    properties:
      hostPlayer:
        type: string
      invitedPlayers:
        type: object
  NewGameSuccessResponse:
      type: object
      properties:
        gameCreated:
          type: boolean
        gameId:
          type: integer
  NewGameFailedResponse:
      type: object
      properties:
        gameCreated:
          type: boolean
        reason:
          type: string
  GameInfo:
    type: object
    properties:
      gameId:
        type: integer
      players:
        type: object
        properties:
          hostPlayer:
            type: string
          invitedPlayers:
            type: object
          acceptedPlayers:
            type: object
          pendingPlayers:
            type: object
          declinedPlayers:
            type: object
      gameState:
        type: string
